import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ./src/lib/appwrite/types.ts`.

export type Students = Models.Row & {
    name: string;
    email: string | null;
    userId: string;
    archivedAt: string | null;
    tutoringSessions: TutoringSessions[];
    paymentConfirmations: PaymentConfirmations[];
}

export type Subjects = Models.Row & {
    name: string;
    color: string | null;
    userId: string;
    tutoringSessions: TutoringSessions[];
}

export type TutoringSessions = Models.Row & {
    date: string;
    duration: number | null;
    notes: string | null;
    completedAt: string | null;
    cancelledAt: string | null;
    userId: string;
    student: Students;
    subject: Subjects;
    paidAt: string | null;
    amountPaid: number | null;
    paymentConfirmations: PaymentConfirmations[];
}

export type PaymentConfirmations = Models.Row & {
    userId: string;
    template: DocumentTemplates;
    sessions: TutoringSessions[];
    student: Students;
}

export type DocumentTemplates = Models.Row & {
    name: string;
    userId: string;
    template: string;
    paymentConfirmations: PaymentConfirmations[];
}
