import type { Models } from "appwrite";

/**
 * Fields generated by Appwrite that we shouldn't send during creation for nested items.
 */
export type AppwriteSystemFields = keyof Models.Row;

/**
 * Child-level Transformation:
 * 1. Strips system fields ($id, $createdAt, etc.).
 * 2. Identifies Relationships (anything extending Models.Row) and makes them optional.
 * 3. Preserves standard data arrays (string[], number[]).
 */
type ModelCreateRecursive<T> = T extends object
  ? {
      // OPTIONAL: Nullables OR Relationships (Models.Row)
      [K in keyof Omit<T, AppwriteSystemFields> as
        | (null extends T[K] ? K : never)
        | (T[K] extends Models.Row ? K : never)
        | (T[K] extends Models.Row[] ? K : never)]?: T[K] extends (infer U)[]
        ? U extends Models.Row
          ? ModelCreateRecursive<U>[] | null | undefined
          : T[K]
        : T[K] extends Models.Row
          ? ModelCreateRecursive<T[K]> | null | undefined
          : T[K] | undefined;
    } & {
      // REQUIRED: Non-nullable primitives and data arrays
      [K in keyof Omit<T, AppwriteSystemFields> as null extends T[K]
        ? never
        : T[K] extends Models.Row
          ? never
          : T[K] extends Models.Row[]
            ? never
            : K]: T[K];
    } & {
      $permissions?: string[];
    }
  : T;

/**
 * Top-level Entry Point:
 * Strictly preserves the root Row structure while recursing into custom relationships.
 */
export type ModelCreate<T> = Pick<T, Extract<keyof T, keyof Models.Row>> & {
  [K in keyof Omit<T, keyof Models.Row> as
    | (null extends T[K] ? K : never)
    | (T[K] extends Models.Row ? K : never)
    | (T[K] extends Models.Row[] ? K : never)]?: T[K] extends (infer U)[]
    ? U extends Models.Row
      ? ModelCreateRecursive<U>[] | null | undefined | string[]
      : T[K]
    : T[K] extends Models.Row
      ? ModelCreateRecursive<T[K] | string> | null | undefined
      : T[K] | undefined;
} & {
  [K in keyof Omit<T, keyof Models.Row> as null extends T[K]
    ? never
    : T[K] extends Models.Row
      ? never
      : T[K] extends Models.Row[]
        ? never
        : K]: T[K];
};

export type ModelUpdate<T> = Exclude<
  Partial<ModelCreate<T>>,
  keyof Models.Row
> &
  Pick<T, Extract<keyof T, keyof Models.Row>>;
