/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSubjectsRouteImport } from './routes/app/subjects'
import { Route as AppStudentsRouteImport } from './routes/app/students'
import { Route as AppTemplatesIndexRouteImport } from './routes/app/templates/index'
import { Route as AppSessionsIndexRouteImport } from './routes/app/sessions/index'
import { Route as AppConfirmationsIndexRouteImport } from './routes/app/confirmations/index'
import { Route as AppTemplatesNewRouteImport } from './routes/app/templates/new'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/app/templates/$templateId'
import { Route as AppSessionsSessionIdRouteImport } from './routes/app/sessions/$sessionId'
import { Route as AppConfirmationsConfirmationIdRouteImport } from './routes/app/confirmations/$confirmationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfirmationsIndexRoute = AppConfirmationsIndexRouteImport.update({
  id: '/confirmations/',
  path: '/confirmations/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppConfirmationsConfirmationIdRoute =
  AppConfirmationsConfirmationIdRouteImport.update({
    id: '/confirmations/$confirmationId',
    path: '/confirmations/$confirmationId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/confirmations/$confirmationId': typeof AppConfirmationsConfirmationIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/templates/new': typeof AppTemplatesNewRoute
  '/app/confirmations/': typeof AppConfirmationsIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app': typeof AppIndexRoute
  '/app/confirmations/$confirmationId': typeof AppConfirmationsConfirmationIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/templates/new': typeof AppTemplatesNewRoute
  '/app/confirmations': typeof AppConfirmationsIndexRoute
  '/app/sessions': typeof AppSessionsIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/confirmations/$confirmationId': typeof AppConfirmationsConfirmationIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/templates/new': typeof AppTemplatesNewRoute
  '/app/confirmations/': typeof AppConfirmationsIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/students'
    | '/app/subjects'
    | '/app/'
    | '/app/confirmations/$confirmationId'
    | '/app/sessions/$sessionId'
    | '/app/templates/$templateId'
    | '/app/templates/new'
    | '/app/confirmations/'
    | '/app/sessions/'
    | '/app/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/students'
    | '/app/subjects'
    | '/app'
    | '/app/confirmations/$confirmationId'
    | '/app/sessions/$sessionId'
    | '/app/templates/$templateId'
    | '/app/templates/new'
    | '/app/confirmations'
    | '/app/sessions'
    | '/app/templates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/students'
    | '/app/subjects'
    | '/app/'
    | '/app/confirmations/$confirmationId'
    | '/app/sessions/$sessionId'
    | '/app/templates/$templateId'
    | '/app/templates/new'
    | '/app/confirmations/'
    | '/app/sessions/'
    | '/app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/': {
      id: '/app/sessions/'
      path: '/sessions'
      fullPath: '/app/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/confirmations/': {
      id: '/app/confirmations/'
      path: '/confirmations'
      fullPath: '/app/confirmations/'
      preLoaderRoute: typeof AppConfirmationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/new': {
      id: '/app/templates/new'
      path: '/templates/new'
      fullPath: '/app/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/$templateId': {
      id: '/app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId': {
      id: '/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/confirmations/$confirmationId': {
      id: '/app/confirmations/$confirmationId'
      path: '/confirmations/$confirmationId'
      fullPath: '/app/confirmations/$confirmationId'
      preLoaderRoute: typeof AppConfirmationsConfirmationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfirmationsConfirmationIdRoute: typeof AppConfirmationsConfirmationIdRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppConfirmationsIndexRoute: typeof AppConfirmationsIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfirmationsConfirmationIdRoute: AppConfirmationsConfirmationIdRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppConfirmationsIndexRoute: AppConfirmationsIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
